<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon; // Import Carbon for timestamp generation

class FarmerSeeder extends Seeder
{
    public function run()
    {
        $data = [
            ['Teodulo R. Alvarez', 4, 1.50, 'Vegetable'],
            ['Daniel T. Escasura', 4, 1.00, 'Vegetable'],
            ['Estela A. Galang', 4, 1.00, 'Vegetable'],
            ['Anaclito O. Bonite', 6, 1.50, 'Vegetable'],
            ['Angelito L. Ramilo Jr.', 6, 1.00, 'Vegetable'],
            ['Domingo G. Olicia', 6, 0.50, 'Vegetable'],
            ['Edgardo G. Olicia', 6, 0.70, 'Vegetable'],
            ['Ernesto C. Rufo', 6, 2.00, 'Vegetable'],
            ['Felimon G. Carcueva', 6, 0.50, 'Vegetable'],
            ['Flaviano P. Capagua', 6, 0.60, 'Vegetable'],
            ['Monina N. Abano', 6, 0.30, 'Vegetable'],
            ['Senando L. Alegre', 6, 1.00, 'Vegetable'],
            ['Serafin B. Saturno', 6, 1.00, 'Vegetable'],
            ['Monina M. Abano', 6, 0.30, 'Vegetable'],
            ['Senando L. Alegre', 6, 1.00, 'Vegetable'],
            ['Agapito G. Soriano', 6, 10.00, 'Vegetable'],
            ['Bernardo S. Naraga', 5, 0.50, 'Vegetable'],
            ['Crispin A. Nevalga', 5, 1.00, 'Vegetable'],
            ['Dionicio A. Capuso', 5, 1.00, 'Vegetable'],
            ['Donato D. Irom', 5, 1.50, 'Vegetable'],
            ['Ireneo L. Lat', 5, 1.00, 'Vegetable'],
            ['Jessie James M. Diaz', 5, 3.00, 'Vegetable'],
            ['Manuel A. Completo', 5, 0.50, 'Vegetable'],
            ['Marcelo A. Elomina', 5, 1.00, 'Vegetable'],
            ['Marilyn R. Ebdani', 5, 0.40, 'Vegetable'],
            ['Mark Anthony O. Castelo', 5, 1.50, 'Vegetable'],
            ['Maximo Nataya', 5, 1.00, 'Vegetable'],
            ['Merici L. Ednalino', 5, 1.50, 'Vegetable'],
            ['Myra A. Delos Santos', 5, 3.00, 'Vegetable'],
            ['Nick Valdez', 5, 1.00, 'Vegetable'],
            ['Pastor L. Nevalga', 5, 1.50, 'Vegetable'],
            ['Policarpio A. Talibsao', 5, 0.50, 'Vegetable'],
            ['Roman A. Nataya', 5, 1.00, 'Vegetable'],
            ['Rufo B. Aliparo', 5, 0.50, 'Vegetable'],
            ['Vevencio M. Nayve', 5, 1.00, 'Vegetable'],
            ['Josefina C. Matundan', 7, 0.50, 'Vegetable'],
            ['Julie T. Matundan', 7, 0.50, 'Vegetable'],
            ['Marcial B. Galang', 7, 0.50, 'Vegetable'],
            ['Alexander O. Olabiaga', 7, 1.00, 'Vegetable'],
            ['Nonilon C. Roberto', 7, 14.50, 'Vegetable'],
            ['Gaudencio M. Gonzales II', 12, 1.50, 'Vegetable'],
            ['Juanito D. Andal', 12, 1.00, 'Vegetable'],
            ['Angelito A. Yanes', 1, 0.80, 'Vegetable'],
            ['Antonino C. Lazanas', 1, 1.20, 'Vegetable'],
            ['Bernardo T. Cansicio', 1, 2.00, 'Vegetable'],
            ['Candy C. Galang', 1, 1.40, 'Vegetable'],
            ['Cayetano M. Tumagcao', 1, 1.30, 'Vegetable'],
            ['Dante V. Aldueza', 1, 1.20, 'Vegetable'],
            ['Dionisio Tumagcao', 1, 1.50, 'Vegetable'],
            ['Dolores L. Algire', 1, 1.00, 'Vegetable'],
            ['Domingo C. Gecana', 1, 1.50, 'Vegetable'],
            ['Donato G. Rivera', 1, 0.90, 'Vegetable'],
            ['Edgardo J. Magpugay', 1, 1.10, 'Vegetable'],
            ['Edilberto A. Gimutao', 1, 0.80, 'Vegetable'],
            ['Eduardo B. Galang', 1, 1.40, 'Vegetable'],
            ['Emiliano M. Gimutao', 1, 3.00, 'Vegetable'],
            ['Frisco A. Gimutao', 1, 0.70, 'Vegetable'],
            ['Jerry Y. Alarcon', 1, 1.20, 'Vegetable'],
            ['Jonathan L. Mendoza', 1, 1.00, 'Vegetable'],
            ['Jonel P. Ogbac', 1, 0.70, 'Vegetable'],
            ['Jovielyd E. Balotabot', 1, 1.00, 'Vegetable'],
            ['Lauro A. Perez', 1, 3.00, 'Vegetable'],
            ['Leonardo D. Algire', 1, 1.00, 'Vegetable'],
            ['Luisito R. Lavina', 1, 1.60, 'Vegetable'],
            ['Lydia C. Jastillana', 1, 1.00, 'Vegetable'],
            ['Manolito M. Hatulan', 1, 0.60, 'Vegetable'],
            ['Manuel A. Contreras', 1, 1.00, 'Vegetable'],
            ['Manuel L. Ramos', 1, 1.90, 'Vegetable'],
            ['Manuel R. Arroyo', 1, 0.70, 'Vegetable'],
            ['Marilou C. Gimutao', 1, 1.00, 'Vegetable'],
            ['Mario V. Tatlonghari', 1, 1.20, 'Vegetable'],
            ['Marlon R. Besmonte', 1, 1.00, 'Vegetable'],
            ['Maximo M. Managat', 1, 0.80, 'Vegetable'],
            ['Merlita B. Barrenechea', 1, 1.50, 'Vegetable'],
            ['Minerva O. Olatan', 1, 0.70, 'Vegetable'],
            ['Myleen D. Parohinog', 1, 0.50, 'Vegetable'],
            ['Nilo L. Lazanas', 1, 2.00, 'Vegetable'],
            ['Norlito J. Unida', 1, 1.50, 'Vegetable'],
            ['Pepito M. Terrones', 1, 0.80, 'Vegetable'],
            ['Princess C. Saga', 1, 2.00, 'Vegetable'],
            ['Ramon P. Ramos', 1, 1.10, 'Vegetable'],
            ['Reynaldo A. Sigua', 1, 1.10, 'Vegetable'],
            ['Ricardo P. Cruz', 1, 2.50, 'Vegetable'],
            ['Rodnie F. Gimarangan', 1, 5.00, 'Vegetable'],
            ['Romeo G. Aldave', 1, 2.00, 'Vegetable'],
            ['Rommel J. Gimutao', 1, 2.50, 'Vegetable'],
            ['Ronaldo C. Hatulan', 1, 0.80, 'Vegetable'],
            ['Roque R. Besmonte Jr.', 1, 1.00, 'Vegetable'],
            ['Rufino A. Sigua', 1, 0.90, 'Vegetable'],
            ['Zayrus R. Arroyo', 1, 1.20, 'Vegetable'],
            ['Gina M. Broncano', 3, 0.50, 'Vegetable'],
            ['Necitas B. Geneciran', 3, 0.50, 'Vegetable'],
            ['Alvin I. Rosana', 3, 1.20, 'Vegetable'],
            ['Jonathan A. Francisco', 3, 2.00, 'Vegetable'],
            ['Efren B. Ercia', 3, 2.00, 'Vegetable'],
            ['Alvin D. Juanata', 2, 1.00, 'Vegetable'],
            ['Ana Maria L. Pabale', 2, 1.80, 'Vegetable'],
            ['Benjamin A. Capati', 2, 0.60, 'Vegetable'],
            ['Beverly L. Diche', 2, 1.50, 'Vegetable'],
            ['Crispin C. Barayang', 2, 3.70, 'Vegetable'],
            ['Dennis B. Tatlonghari', 2, 3.00, 'Vegetable'],
            ['Donnel C. Tabafunda', 2, 2.50, 'Vegetable'],
            ['Edmon G. Alcalde', 2, 1.50, 'Vegetable'],
            ['Eduardo F. Lauguico', 2, 1.30, 'Vegetable'],
            ['Evangeline G. Tatlonghari', 2, 1.20, 'Vegetable'],
            ['Francisco T. Lirio', 2, 0.60, 'Vegetable'],
            ['Helen M. Guanzon', 10, 1.00, 'Vegetable'],
            ['Ireneo A. Baroro', 2, 1.00, 'Vegetable'],
            ['Isagani C. Galang', 2, 1.50, 'Vegetable'],
            ['John P. De Borja', 2, 0.90, 'Vegetable'],
            ['Josephine B. Botin', 2, 1.00, 'Vegetable'],
            ['Julieta D. Trinos', 2, 1.00, 'Vegetable'],
            ['Lucio S. Galang', 2, 1.50, 'Vegetable'],
            ['Ma. Teresa T. Digol', 2, 1.00, 'Vegetable'],
            ['Mario B. Trinos', 2, 2.00, 'Vegetable'],
            ['Medel B. Tatlonghari', 2, 2.50, 'Vegetable'],
            ['Mely D. Juanata', 2, 1.00, 'Vegetable'],
            ['Ramon S. Librada', 2, 1.50, 'Vegetable'],
            ['Randy B. Trinos', 2, 1.00, 'Vegetable'],
            ['Raquel D. Galang', 2, 0.50, 'Vegetable'],
            ['Renato C. Sayasaya', 2, 1.00, 'Vegetable'],
            ['Roberto A. Cabrera', 2, 1.50, 'Vegetable'],
            ['Rodrigo M. Cruz', 2, 1.50, 'Vegetable'],
            ['Roginald B. Jastillana', 2, 1.20, 'Vegetable'],
            ['Rolando D. Amarante', 2, 0.70, 'Vegetable'],
            ['Rolando S. Allasas', 2, 1.50, 'Vegetable'],
            ['Romeo B. Tatlonghari', 2, 2.00, 'Vegetable'],
            ['Romeo S. Severino', 2, 2.10, 'Vegetable'],
            ['Romualdo G. Diche', 2, 0.80, 'Vegetable'],
            ['Teodoro A. Jastillana', 2, 1.30, 'Vegetable'],
            ['Tirso P. Gumahod', 2, 1.00, 'Vegetable'],
            ['Vicenta D. Parala', 2, 1.50, 'Vegetable'],
            ['Marina C. Baron', 8, 1.00, 'Vegetable'],
            ['Salustino C. Baron', 8, 0.60, 'Vegetable'],
            ['Bonifacio G. Capati', 8, 1.00, 'Vegetable'],
            ['Jayson M. Completo', 8, 1.50, 'Vegetable'],
            ['Lorenzo M. Completo', 8, 1.50, 'Vegetable'],
            ['Roberto C. Completo', 8, 1.50, 'Vegetable'],
            ['Victoria B. Evangelista', 8, 0.40, 'Vegetable'],
            ['German Oliver B. Hain', 8, 2.00, 'Vegetable'],
            ['Lamberto G. Palis', 8, 1.20, 'Vegetable'],
            ['Maricar B. Teves', 8, 0.70, 'Vegetable'],
            ['Alexander M. Advincula', 9, 1.00, 'Vegetable'],
            ['Avenger E. Baldugo', 9, 1.00, 'Vegetable'],
            ['Emily J. Liza', 9, 0.50, 'Vegetable'],
            ['Emily J. Liza', 9, 0.50, 'Vegetable'],
            ['Leonisa M. Acuna', 9, 1.00, 'Vegetable'],
            ['Mark Anthony O. Garcera', 9, 0.70, 'Vegetable'],
            ['Nenneth G. Garing', 9, 0.70, 'Vegetable'],
            ['Noel C. Masaganda', 9, 0.50, 'Vegetable'],
            ['Reynaldo C. Acuna', 9, 1.00, 'Vegetable'],
            ['Rodelio A. Sigua', 9, 1.00, 'Vegetable'],
            ['Sotelia B. Cariod', 9, 1.50, 'Vegetable'],
            ['Alvin A. Mabalot', 10, 0.50, 'Vegetable'],
            ['Arson Q. Asido', 10, 0.50, 'Vegetable'],
            ['Edgar A. Hemedes', 10, 1.00, 'Vegetable'],
            ['Edgar C. Geral', 10, 0.60, 'Vegetable'],
            ['Ferdinand A. Hemedes', 10, 1.00, 'Vegetable'],
            ['Godofredo P. Ginaga', 10, 0.50, 'Vegetable'],
            ['Gregorio L. Barundia', 10, 0.50, 'Vegetable'],
            ['Helen M. Guanzon', 10, 0.50, 'Vegetable'],
            ['Jimmy F. Santiago', 10, 1.00, 'Vegetable'],
            ['Jose Melvin D. Punongbayan', 10, 1.00, 'Vegetable'],
            ['Juan L. Benedicto', 10, 0.60, 'Vegetable'],
            ['Librada S. Hercia', 10, 0.90, 'Vegetable'],
            ['Melvin D. Punongbayan', 10, 1.00, 'Vegetable'],
            ['Nelson F. Asido', 10, 0.50, 'Vegetable'],
            ['Nicomedes O. Canceran', 10, 0.50, 'Vegetable'],
            ['Renee A. Ulan', 10, 0.70, 'Vegetable'],
            ['Ronnie Q. Asido', 10, 0.50, 'Vegetable'],
            ['Rowena M. Cervantes', 10, 1.00, 'Vegetable'],
            ['Severiano B. Hain', 10, 1.50, 'Vegetable'],
            ['Teresito C. Cantillan', 10, 2.50, 'Vegetable'],
            ['Alfredo B. Lameseria Jr.', 11, 1.00, 'Vegetable'],
            ['Arnolito L. Lizada', 11, 1.50, 'Vegetable'],
            ['Benedick U. Canceran', 11, 0.80, 'Vegetable'],
            ['Bernardo B. Garcera', 11, 0.80, 'Vegetable'],
            ['Dennis G. Lucinada', 11, 0.90, 'Vegetable'],
            ['Diosdado D. Arnaldo', 11, 0.80, 'Vegetable'],
            ['Edgar L. Cantillano', 11, 0.80, 'Vegetable'],
            ['Edgardo S. Lavina', 11, 0.70, 'Vegetable'],
            ['Elmo V. Republica', 11, 1.50, 'Vegetable'],
            ['Enrique P. Bercasio', 11, 0.50, 'Vegetable'],
            ['Estelita D. Sangcajo', 11, 0.80, 'Vegetable'],
            ['Evangeline R. Panghulan', 11, 1.00, 'Vegetable'],
            ['Fernando L. Cruz', 11, 0.60, 'Vegetable'],
            ['Fernando S. Carbajosa', 11, 2.00, 'Vegetable'],
            ['Giblas V. Garcera', 11, 0.80, 'Vegetable'],
            ['Gino K. Saga', 11, 1.80, 'Vegetable'],
            ['Jerry L. Gazzingan', 11, 3.00, 'Vegetable'],
            ['Joel L. Bautista', 11, 0.80, 'Vegetable'],
            ['John Michael O. Gazzingan', 11, 1.00, 'Vegetable'],
            ['Joselito L. Cantillano', 11, 0.30, 'Vegetable'],
            ['Joselito P. Algire', 11, 0.80, 'Vegetable'],
            ['Luisito A. Patron', 11, 1.00, 'Vegetable'],
            ['Nestor P. Algire', 11, 0.70, 'Vegetable'],
            ['Pablo L. Saturno', 11, 0.70, 'Vegetable'],
            ['Pedro G. Algire', 11, 1.30, 'Vegetable'],
            ['Quintin B. Devoma', 11, 1.20, 'Vegetable'],
            ['Reynaldo L. Cometa', 11, 0.80, 'Vegetable'],
            ['Reynalin R. Olan', 11, 0.80, 'Vegetable'],
            ['Roderick L. Cruz', 11, 0.70, 'Vegetable'],
            ['Ronaldo A. Sigua', 11, 0.80, 'Vegetable'],
            ['Ronie A. Comita', 11, 1.00, 'Vegetable'],
            ['Ronie S. Patron', 11, 0.90, 'Vegetable'],
            ['Ruben O. Patron', 11, 1.50, 'Vegetable'],
            ['Teodulo G. Algire', 11, 0.70, 'Vegetable'],
            ['Thelma B. Sigua', 11, 1.00, 'Vegetable'],
            ['Zorayda D. Leonor', 11, 0.80, 'Vegetable'],
            ['Teodulo Ramos Alvarez', 4, 1.80, 'Rice'],
            ['Imelda V. Capacio', 6, 2.40, 'Rice'],
            ['Danilo Matillano Casabon', 5, 3.70, 'Rice'],
            ['Guillermino Almonia Ama', 7, 1.50, 'Rice'],
            ['Jerry Yoga Alarcon', 1, 1.50, 'Rice'],
            ['Policarpia Nelia Lapaz Bariring', 3, 1.00, 'Rice'],
            ['Ma. Soledad Talibsao Afuang', 2, 1.50, 'Rice'],
            ['Leonisa Mulinyawe Acuña', 9, 2.30, 'Rice'],
            ['Elvira Del Rosario Antioquia', 8, 1.70, 'Rice'],
            ['Mark Alfred Antiporta', 10, 1.50, 'Rice'],
            ['Alexander Mallo Advincula', 11, 1.70, 'Rice'],
        ];

        foreach ($data as $record) {
            DB::table('farmers')->insert([
                'barangayId' => $record[1],
                'farmerName' => $record[0],
                'fieldArea' => $record[2],
                'fieldType' => $record[3],
                'created_at' => Carbon::now(), // Current timestamp
                'updated_at' => Carbon::now(), // Current timestamp
            ]);
        }
    }
}
